# Generated by Django 4.2 on 2023-05-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="age",
        ),
        migrations.AlterField(
            model_name="author",
            name="date_birthd",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="author",
            name="surname",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Фамилия"
            ),
        ),
    ]
