# Generated by Django 4.2 on 2023-04-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_alter_author_options_alter_book_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="api_key",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="API ключ"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="published",
            field=models.DateField(verbose_name="Дата публикации"),
        ),
    ]
