# Generated by Django 4.2 on 2023-04-30 16:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_author_api_key_alter_book_published"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="api_key",
        ),
    ]
