# Generated by Django 4.2 on 2023-05-01 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0003_alter_book_published"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="author",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="author",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="author",
            name="email",
        ),
        migrations.RemoveField(
            model_name="author",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="author",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="author",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="author",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="author",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="author",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="author",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="author",
            name="password",
        ),
        migrations.RemoveField(
            model_name="author",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="author",
            name="username",
        ),
        migrations.AddField(
            model_name="author",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="catalog.author",
                verbose_name="Автор",
            ),
        ),
    ]
